In [2]:
import pandas as pd
from pip._internal import locations

ngay = ['1/3', '2/3', '3/3', '4/3', '5/3', '6/3', '7/3']
giaban = [46, 47, 46, 45, 46, 46, 45]
giamua = [45, 46, 45.5, 44.5, 45, 45.5, 44.5]
dulieu = zip(ngay, giaban, giamua)
df = pd.DataFrame(data = dulieu)
df.to_csv('Banggiavang.csv', index = False, header = False)

In [6]:
location = "Banggiavang.csv"
df = pd.read_csv(location)
df.columns = ['Ngày', 'Giá vàng bán ra', 'Giá vàng mua vào']
df.head()

  Ngày  Giá vàng bán ra  Giá vàng mua vào
0  2/3               47              46.0
1  3/3               46              45.5
2  4/3               45              44.5
3  5/3               46              45.0
4  6/3               46              45.5

In [11]:
import pandas as pd

ten = ['Trung', 'Cảnh', 'Bảo', 'Quốc', 'Tùng']
vangLT = [3, 5, 1, 0, 2]
vangTT = [2, 1, 0, 0, 1]
khongNB = [0, 3, 0, 2, 1]
duLieu = zip(ten, vangLT, vangTT, khongNB)
df = pd.DataFrame(data = duLieu)
df.to_csv('vipham.csv', index = False, header = False)

In [12]:
Location = "vipham.csv"
df = pd.read_csv(Location)
df.columns = ['Tên SV', 'Vắng LT', 'Vắng TT', 'Không NB' ]
df.head()

  Tên SV  Vắng LT  Vắng TT  Không NB
0   Cảnh        5        1         3
1    Bảo        1        0         0
2   Quốc        0        0         2
3   Tùng        2        1         1

In [36]:
import pandas as pd

hoten = ['Nguyễn Thị Lệ', 'Lê Văn Tài', 'Hồ Hữu Hoàn', 'Lý Thị Lựu', 'Trần Trọng Trí', 'Nguyễn Thị Lệ', 'Phè Văn Phởn']
ngaysinh = ['01/01/45', '21/10/76', '03/03/90', '30/04/01', '01/09/63', '01/01/45', '22/09/04']
gioitinh = ['Nữ', 'Nam','Nam','Nữ', 'Nam','Nữ', 'Nam']
td_CN = [1, 1, 0, 1, 1, 1, 1]
td_ThS = [1, 2, 0, 1, 0, 1, 1]
td_TS = [0, 1, 0, 0, 0, 0, 1]
sodt = ["0915030909", "0902524444", "0232321234", "0170239311", "0904031234", "0915030909", "0907234445"]
dulieu1 = list(zip(hoten, ngaysinh, gioitinh, td_CN, td_ThS, td_TS, sodt))
df = pd.DataFrame(dulieu1, columns=['hoten', 'ngaysinh', 'gioitinh', 'td_CN', 'td_ThS', 'td_TS', 'sodt'])
print(df)
df.to_csv('danhsach.csv', index=False)

            hoten  ngaysinh gioitinh  td_CN  td_ThS  td_TS        sodt
0   Nguyễn Thị Lệ  01/01/45       Nữ      1       1      0  0915030909
1      Lê Văn Tài  21/10/76      Nam      1       2      1  0902524444
2     Hồ Hữu Hoàn  03/03/90      Nam      0       0      0  0232321234
3      Lý Thị Lựu  30/04/01       Nữ      1       1      0  0170239311
4  Trần Trọng Trí  01/09/63      Nam      1       0      0  0904031234
5   Nguyễn Thị Lệ  01/01/45       Nữ      1       1      0  0915030909
6    Phè Văn Phởn  22/09/04      Nam      1       1      1  0907234445

In [55]:
df_gt = pd.get_dummies(df['gioitinh'])
df_new = df.join(df_gt)
df_new = pd.concat([df, df_gt], axis=1)
# Xây dựng hàm chuyển đổi giá trị
def score_to_numeric(x):
    if x=='Nam':
        return 1
    if x=='Nữ':
        return 0
# Gọi hàm chuyển đổi giá trị cho trường Giới tính
df_new.gioitinh = df_new.gioitinh.apply(score_to_numeric)
df_new.duplicated()
df_trung = df_new.drop_duplicates()
#Tạo tập tin dữ liệu data01.csv
df_trung.to_csv('data01.csv',index=False,header=True)
print(df_trung)

            hoten  ngaysinh  gioitinh  td_CN  td_ThS  td_TS        sodt  \
0   Nguyễn Thị Lệ  01/01/45         0      1       1      0  0915030909
1      Lê Văn Tài  21/10/76         1      1       2      1  0902524444
2     Hồ Hữu Hoàn  03/03/90         1      0       0      0  0232321234
3      Lý Thị Lựu  30/04/01         0      1       1      0  0170239311
4  Trần Trọng Trí  01/09/63         1      1       0      0  0904031234
6    Phè Văn Phởn  22/09/04         1      1       1      1  0907234445

     Nam     Nữ
0  False   True
1   True  False
2   True  False
3  False   True
4   True  False
6   True  False

In [76]:
location2 = "data01.csv"
df = pd.read_csv(location2)
#Xóa cột Nam Nữ
df = df.drop('Nam', axis=1)
df = df.drop('Nữ', axis=1)

#Thêm cột Hưu trí với giá trị với dãy giá trị cho trước
d = ([1,0,0,1,0,1])
s = pd.Series(d, index= df.index)
df['Huutri'] = s

#Thêm cột hệ số lương với giá trị cho trước
d = ([6.4,3.99,2.97,5.4,4.2,8.2])
s = pd.Series(d, index= df.index)
df['hsl'] = s

#Thêm cột lương cơ bản với giá trị bằng Hệ số lương*1350000
l = df['hsl']*1350000
s = pd.Series(l, index= df.index)
df['luongcb'] = s

#Đổi tên cột sang chữ thường, ký tự đầu là ký tự hoa
df.columns = map(str.lower, df.columns)

# Xây dựng hàm chuyển đổi giá trị
def score_to_num(x):
    if x==0:
        return 0
    if x>=1:
        return 1
print (df)
df.to_csv('data02.csv',index=False,header=True)

            hoten  ngaysinh  gioitinh  td_cn  td_ths  td_ts       sodt  \
0   Nguyễn Thị Lệ  01/01/45         0      1       1      0  915030909
1      Lê Văn Tài  21/10/76         1      1       2      1  902524444
2     Hồ Hữu Hoàn  03/03/90         1      0       0      0  232321234
3      Lý Thị Lựu  30/04/01         0      1       1      0  170239311
4  Trần Trọng Trí  01/09/63         1      1       0      0  904031234
5    Phè Văn Phởn  22/09/04         1      1       1      1  907234445

   huutri   hsl     luongcb
0       1  6.40   8640000.0
1       0  3.99   5386500.0
2       0  2.97   4009500.0
3       1  5.40   7290000.0
4       0  4.20   5670000.0
5       1  8.20  11070000.0

In [79]:
import numpy as np
location3 = "data02.csv"
df = pd.read_csv(location3)
#Lọc cột
#df[['hoten','ngaysinh','gioitinh']].head()
#Lọc dòng
#df[:3]
#Để hiển thị những bản ghi thỏa điều kiện
#df.loc[df['hoten'].str.contains('Thị')==True]
#Lọc những bản ghi có giới tính 1
#df[df['gioitinh'] == 1]
#Lọc những bản ghi có giới tính là 0 và hưu trí là 1
#df[(df['gioitinh'] == 0) & (df['huutri'] == 1)]
#Lọc những bản ghi có giới tính là 0 hoặc trình độ tiến sỹ là 1
#df[(df['gioitinh'] == 0) | (df['td_ts'] == 1)]
#lấy 3 dòng dữ liệu một cách ngẫu nhiên
#df.take(np.random.permutation(len(df))[:3])

,hoten,ngaysinh,gioitinh,td_cn,td_ths,td_ts,sodt,huutri,hsl,luongcb
0,Nguyễn Thị Lệ,01/01/45,0,1,1,0,915030909,1,6.4,8640000.0
3,Lý Thị Lựu,30/04/01,0,1,1,0,170239311,1,5.4,7290000.0